import {
  FiUser,
  FiDollarSign,
  FiCalendar,
  FiBook,
  FiFileText,
  FiClock,
  FiGrid,
  FiBookOpen,
  FiCheckSquare,
  FiClipboard,
  FiArchive,
  FiBookmark,
  FiPieChart,
  FiList,
  FiCoffee,
  FiAward,
  FiBarChart2,
  FiCheckCircle,
  FiStar,
  FiUpload,
  FiDownload,
  FiTarget,
  FiLayers,
  FiTrendingUp,
  FiDatabase,
} from "react-icons/fi";

export const dashboardFeatures = [
  {
    id: "staff-info",
    title: "Staff Information",
    description: "Manage your personal and professional details",
    icon: FiUser,
    sections: [
      "personal",
      "academic",
      "research",
      "employer",
      "service",
      "biodata",
    ],
  },
  {
    id: "my-classes",
    title: "My Classes",
    description: "View and manage your current and archived classes",
    icon: FiBookOpen,
    sections: ["current", "archived"],
  },
  {
    id: "tutorship",
    title: "My Tutorship",
    description: "Monitor and manage your assigned student batch",
    icon: FiBook,
    sections: [
      "batch-details",
      "academic-records",
      "scholarships",
      "credit-approvals",
      "achievements",
    ],
  },
  {
    id: "copo",
    title: "CO-PO Computation",
    description: "Calculate and analyze Course Outcomes and Program Outcomes",
    icon: FiTarget,
    sections: [
      "internal-assessment",
      "high-level-mapping",
      "detailed-analysis",
      "reports",
      "templates",
    ],
  },
  {
    id: "result-analysis",
    title: "KTU Result Analysis",
    description: "Generate and view comprehensive result analysis reports",
    icon: FiTrendingUp,
    sections: [
      "upload-results",
      "generate-analysis",
      "analysis-history",
      "batch-comparison",
    ],
  },
  {
    id: "tax",
    title: "Tax Management",
    description: "Handle your tax calculations, declarations and documents",
    icon: FiDollarSign,
    sections: ["calculator", "declarations", "documents", "history"],
  },
  {
    id: "leave",
    title: "Leave Management",
    description: "Apply and track your leave requests",
    icon: FiCalendar,
    sections: ["apply", "history"],
  },
  {
    id: "schedule",
    title: "My Schedule",
    description: "View and manage your daily schedule and activities",
    icon: FiClock,
    sections: ["timetable", "activities", "meetings"],
  },
];

export const navigationItems = {
  "staff-info": [
    { name: "Personal Information", icon: FiUser, section: "personal" },
    { name: "Academic Details", icon: FiBook, section: "academic" },
    { name: "Research Activities", icon: FiFileText, section: "research" },
    { name: "Employer Details", icon: FiGrid, section: "employer" },
    { name: "Service Details", icon: FiClock, section: "service" },
    { name: "Biodata", icon: FiFileText, section: "biodata" },
  ],
  "my-classes": [
    { name: "Current Classes", icon: FiBookOpen, section: "current" },
    { name: "Archived Classes", icon: FiArchive, section: "archived" },
  ],
  tutorship: [
    { name: "Batch Details", icon: FiUser, section: "batch-details" },
    {
      name: "Academic Records",
      icon: FiBarChart2,
      section: "academic-records",
    },
    {
      name: "Scholarship Approvals",
      icon: FiCheckCircle,
      section: "scholarships",
    },
    {
      name: "Credit Approvals",
      icon: FiCheckSquare,
      section: "credit-approvals",
    },
    { name: "Student Achievements", icon: FiAward, section: "achievements" },
  ],
  copo: [
    {
      name: "Internal Assessment",
      icon: FiClipboard,
      section: "internal-assessment",
      description: "Upload and process internal marks for CO-PO calculation",
    },
    {
      name: "High-Level Mapping",
      icon: FiLayers,
      section: "high-level-mapping",
      description: "Define CO-PO mapping matrix and weightages",
    },
    {
      name: "Detailed Analysis",
      icon: FiBarChart2,
      section: "detailed-analysis",
      description: "Complete CO-PO computation with all components",
    },
    {
      name: "Generated Reports",
      icon: FiDownload,
      section: "reports",
      description: "View and download generated CO-PO reports",
    },
    {
      name: "Upload Templates",
      icon: FiUpload,
      section: "templates",
      description: "Download and upload standardized templates",
    },
  ],
  "result-analysis": [
    {
      name: "Upload Results",
      icon: FiUpload,
      section: "upload-results",
      description: "Upload semester result PDFs for analysis",
    },
    {
      name: "Generate Analysis",
      icon: FiBarChart2,
      section: "generate-analysis",
      description: "Generate Excel reports with comprehensive analysis",
    },
    {
      name: "Analysis History",
      icon: FiDatabase,
      section: "analysis-history",
      description: "View and download previous analysis reports",
    },
    {
      name: "Batch Comparison",
      icon: FiTrendingUp,
      section: "batch-comparison",
      description: "Compare results across different batches and semesters",
    },
  ],
  tax: [
    { name: "Tax Calculator", icon: FiPieChart, section: "calculator" },
    { name: "Tax Declarations", icon: FiFileText, section: "declarations" },
    { name: "Tax Documents", icon: FiClipboard, section: "documents" },
    { name: "History", icon: FiClock, section: "history" },
  ],
  leave: [
    { name: "Apply Leave", icon: FiCalendar, section: "apply" },
    { name: "Leave History", icon: FiClock, section: "history" },
  ],
  schedule: [
    { name: "Timetable", icon: FiList, section: "timetable" },
    { name: "Daily Activities", icon: FiCoffee, section: "activities" },
    { name: "Meetings", icon: FiCalendar, section: "meetings" },
  ],
};
